const MONDAY = 'Monday'
const TUESDAY = 'Tuesday'
const WEDNESDAY = 'Wednesday'
const THURSDAY = 'Thursday'
const FRIDAY = 'Friday'
const SATURDAY = 'Saturday'
const SUNDAY = 'Sunday'

const DAYS_OF_THE_WEEK = [
  MONDAY,
  TUESDAY,
  WEDNESDAY,
  THURSDAY,
  FRIDAY,
  SATURDAY,
  SUNDAY
]

const DAYS_OF_THE_WEEK_MAP = {}
DAYS_OF_THE_WEEK_MAP[MONDAY] = 1
DAYS_OF_THE_WEEK_MAP[TUESDAY] = 2
DAYS_OF_THE_WEEK_MAP[WEDNESDAY] = 3
DAYS_OF_THE_WEEK_MAP[THURSDAY] = 4
DAYS_OF_THE_WEEK_MAP[FRIDAY] = 5
DAYS_OF_THE_WEEK_MAP[SATURDAY] = 6
DAYS_OF_THE_WEEK_MAP[SUNDAY] = 7

export { DAYS_OF_THE_WEEK, DAYS_OF_THE_WEEK_MAP }
